PEP_INDEX = {
    "1": "PEP Purpose and Guidelines by Warsaw, Hylton, Goodger",
    "2": "Procedure for Adding New Modules by Faassen",
    "3": "Guidelines for Handling Bug Reports by  Hylton",
    "4": "Deprecation of Standard Modules by  von Löwis",
    "5": "Guidelines for Language Evolution by  Prescod",
    "6": "Bug Fix Releases by Aahz, Baxter",
    "7": "Style Guide for C Code by GvR",
    "8": "Style Guide for Python Code by  GvR, Warsaw",
    "9": "Sample Plaintext PEP Template by  Warsaw",
    "10": "Voting Guidelines by  Warsaw",
    "11": "Removing support for little used platforms by von Löwis",
    "12": "Sample reStructuredText PEP Template by Goodger, Warsaw",
    "20": "The Zen of Python by  Peters",
    "42": "Feature Requests by Hylton",
    "100": "Python Unicode Integration by Lemburg",
    "101": "Doing Python Releases 101 by Warsaw, GvR",
    "102": "Doing Python Micro Releases by  Baxter, Warsaw, GvR",
    "160": "Python 1.6 Release Schedule by  Drake",
    "200": "Python 2.0 Release Schedule by  Hylton",
    "201": "Lockstep Iteration by Warsaw",
    "202": "List Comprehensions by  Warsaw",
    "203": "Augmented Assignments by  Wouters",
    "204": "Range Literals by Wouters",
    "205": "Weak References by  Drake",
    "206": "Python Advanced Library by  Kuchling",
    "207": "Rich Comparisons by GvR, Ascher",
    "208": "Reworking the Coercion Model by Schemenauer, Lemburg",
    "209": "Multi-dimensional Arrays by Barrett, Oliphant",
    "210": "Decoupling the Interpreter Loop by  Ascher",
    "211": "Adding A New Outer Product Operator by  Wilson",
    "212": "Loop Counter Iteration by Schneider-Kamp",
    "213": "Attribute Access Handlers by  Prescod",
    "214": "Extended Print Statement by Warsaw",
    "215": "String Interpolation by Yee",
    "216": "Docstring Format by Zadka",
    "217": "Display Hook for Interactive Use by Zadka",
    "218": "Adding a Built-In Set Object Type by  Wilson, Hettinger",
    "219": "Stackless Python by McMillan",
    "220": "Coroutines, Generators, Continuations by  McMillan",
    "221": "Import As by  Wouters",
    "222": "Web Library Enhancements by Kuchling",
    "223": "Change the Meaning of \\x Escapes by Peters",
    "224": "Attribute Docstrings by Lemburg",
    "225": "Elementwise/Objectwise Operators by Zhu, Lielens",
    "226": "Python 2.1 Release Schedule by  Hylton",
    "227": "Statically Nested Scopes by Hylton",
    "228": "Reworking Python's Numeric Model by Zadka, GvR",
    "229": "Using Distutils to Build Python by  Kuchling",
    "230": "Warning Framework by  GvR",
    "231": "__findattr__() by Warsaw",
    "232": "Function Attributes by  Warsaw",
    "233": "Python Online Help by Prescod",
    "234": "Iterators by  Yee, GvR",
    "235": "Import on Case-Insensitive Platforms by Peters",
    "236": "Back to the __future__ by Peters",
    "237": "Unifying Long Integers and Integers by  Zadka, GvR",
    "238": "Changing the Division Operator by Zadka, GvR",
    "239": "Adding a Rational Type to Python by Craig, Zadka",
    "240": "Adding a Rational Literal to Python by  Craig, Zadka",
    "241": "Metadata for Python Software Packages by  Kuchling",
    "242": "Numeric Kinds by  Dubois",
    "243": "Module Repository Upload Mechanism by Reifschneider",
    "244": "The `directive' statement by  von Löwis",
    "245": "Python Interface Syntax by  Pelletier",
    "246": "Object Adaptation by  Martelli, Evans",
    "247": "API for Cryptographic Hash Functions by Kuchling",
    "248": "Python Database API Specification v1.0 by Lemburg",
    "249": "Python Database API Specification v2.0 by Lemburg",
    "250": "Using site-packages on Windows by Moore",
    "251": "Python 2.2 Release Schedule by  Warsaw, GvR",
    "252": "Making Types Look More Like Classes by  GvR",
    "253": "Subtyping Built-in Types by GvR",
    "254": "Making Classes Look More Like Types by  GvR",
    "255": "Simple Generators by  Schemenauer, Peters, Hetland",
    "256": "Docstring Processing System Framework by  Goodger",
    "257": "Docstring Conventions by  Goodger, GvR",
    "258": "Docutils Design Specification by  Goodger",
    "259": "Omit printing newline after newline by  GvR",
    "260": "Simplify xrange() by  GvR",
    "261": "Support for 'wide' Unicode characters by  Prescod",
    "262": "A Database of Installed Python Packages by  Kuchling",
    "263": "Defining Python Source Code Encodings by  Lemburg, von Löwis",
    "264": "Future statements in simulated shells by  Hudson",
    "265": "Sorting Dictionaries by Value by  Griffin",
    "266": "Optimizing Global Variable/Attribute Access by  Montanaro",
    "267": "Optimized Access to Module Namespaces by  Hylton",
    "268": "Extended HTTP functionality and WebDAV by Stein",
    "269": "Pgen Module for Python by Riehl",
    "270": "uniq method for list objects by Petrone",
    "271": "Prefixing sys.path by command line option by  Giacometti",
    "272": "API for Block Encryption Algorithms v1.0 by Kuchling",
    "273": "Import Modules from Zip Archives by Ahlstrom",
    "274": "Dict Comprehensions by  Warsaw",
    "275": "Switching on Multiple Values by Lemburg",
    "276": "Simple Iterator for ints by Althoff",
    "277": "Unicode file name support for Windows NT by Hodgson",
    "278": "Universal Newline Support by  Jansen",
    "279": "The enumerate() built-in function by  Hettinger",
    "280": "Optimizing access to globals by GvR",
    "281": "Loop Counter Iteration with range and xrange by Hetland",
    "282": "A Logging System by Sajip, Mick",
    "283": "Python 2.3 Release Schedule by  GvR",
    "284": "Integer for-loops by  Eppstein, Ewing",
    "285": "Adding a bool type by GvR",
    "286": "Enhanced Argument Tuples by von Löwis",
    "287": "reStructuredText Docstring Format by  Goodger",
    "288": "Generators Attributes and Exceptions by Hettinger",
    "289": "Generator Expressions by  Hettinger",
    "290": "Code Migration and Modernization by Hettinger",
    "291": "Backward Compatibility for the Python 2 Standard ... by Norwitz",
    "292": "Simpler String Substitutions by Warsaw",
    "293": "Codec Error Handling Callbacks by Dörwald",
    "294": "Type Names in the types Module by Tirosh",
    "295": "Interpretation of multiline string constants by Koltsov",
    "296": "Adding a bytes Object Type by Gilbert",
    "297": "Support for System Upgrades by  Lemburg",
    "298": "The Locked Buffer Interface by  Heller",
    "299": "Special __main__() function in modules by Epler",
    "301": "Package Index and Metadata for Distutils by Jones",
    "302": "New Import Hooks by JvR, Moore",
    "303": "Extend divmod() for Multiple Divisors by  Bellman",
    "304": "Controlling Generation of Bytecode Files by Montanaro",
    "305": "CSV File API by Altis, Cole, McNamara, Montanaro, Wells",
    "306": "How to Change Python's Grammar by Hudson, Diederich, Coghlan, Peterson",
    "307": "Extensions to the pickle protocol by  GvR, Peters",
    "308": "Conditional Expressions by  GvR, Hettinger",
    "309": "Partial Function Application by Harris",
    "310": "Reliable Acquisition/Release Pairs by Hudson, Moore",
    "311": "Simplified Global Interpreter Lock Acquisition for ... by Hammond",
    "312": "Simple Implicit Lambda by Suzi, Martelli",
    "313": "Adding Roman Numeral Literals to Python by  Meyer",
    "314": "Metadata for Python Software Packages v1.1 by Kuchling, Jones",
    "315": "Enhanced While Loop by  Hettinger, Carroll",
    "316": "Programming by Contract for Python by Way",
    "317": "Eliminate Implicit Exception Instantiation by Taschuk",
    "318": "Decorators for Functions and Methods by Smith",
    "319": "Python Synchronize/Asynchronize Block by  Pelletier",
    "320": "Python 2.4 Release Schedule by  Warsaw, Hettinger, Baxter",
    "321": "Date/Time Parsing and Formatting by Kuchling",
    "322": "Reverse Iteration by  Hettinger",
    "323": "Copyable Iterators by Martelli",
    "324": "subprocess - New process module by  Astrand",
    "325": "Resource-Release Support for Generators by  Pedroni",
    "326": "A Case for Top and Bottom Values by Carlson, Reedy",
    "327": "Decimal Data Type by  Batista",
    "328": "Imports: Multi-Line and Absolute/Relative by  Aahz",
    "329": "Treating Builtins as Constants in the Standard Library by Hettinger",
    "330": "Python Bytecode Verification by Pelletier",
    "331": "Locale-Independent Float/String Conversions by  Reis",
    "332": "Byte vectors and String/Unicode Unification by  Montanaro",
    "333": "Python Web Server Gateway Interface v1.0 by Eby",
    "334": "Simple Coroutines via SuspendIteration by Evans",
    "335": "Overloadable Boolean Operators by Ewing",
    "336": "Make None Callable by McClelland",
    "337": "Logging Usage in the Standard Library by  Dubner",
    "338": "Executing modules as scripts by Coghlan",
    "339": "Design of the CPython Compiler by Cannon",
    "340": "Anonymous Block Statements by GvR",
    "341": "Unifying try-except and try-finally by  Brandl",
    "342": "Coroutines via Enhanced Generators by GvR, Eby",
    "343": "The 'with' Statement by GvR, Coghlan",
    "344": "Exception Chaining and Embedded Tracebacks by Yee",
    "345": "Metadata for Python Software Packages 1.2 by  Jones",
    "346": "User Defined ('``with``') Statements by Coghlan",
    "347": "Migrating the Python CVS to Subversion by von Löwis",
    "348": "Exception Reorganization for Python 3.0 by  Cannon",
    "349": "Allow str() to return unicode strings by  Schemenauer",
    "350": "Codetags by Elliott",
    "351": "The freeze protocol by  Warsaw",
    "352": "Required Superclass for Exceptions by Cannon, GvR",
    "353": "Using ssize_t as the index type by  von Löwis",
    "354": "Enumerations in Python by Finney",
    "355": "Path - Object oriented filesystem paths by  Lindqvist",
    "356": "Python 2.5 Release Schedule by  Norwitz, GvR, Baxter",
    "357": "Allowing Any Object to be Used for Slicing by Oliphant",
    "358": "The 'bytes' Object by Schemenauer, GvR",
    "359": "The 'make' Statement by Bethard",
    "360": "Externally Maintained Packages by Cannon",
    "361": "Python 2.6 and 3.0 Release Schedule by  Norwitz, Warsaw",
    "362": "Function Signature Object by  Cannon, Seo",
    "363": "Syntax For Dynamic Attribute Access by  North",
    "364": "Transitioning to the Py3K Standard Library by Warsaw",
    "365": "Adding the pkg_resources module by  Eby",
    "366": "Main module explicit relative imports by  Coghlan",
    "367": "New Super by  Spealman, Delaney",
    "368": "Standard image protocol and class by  Mastrodomenico",
    "369": "Post import hooks by  Heimes",
    "370": "Per user site-packages directory by Heimes",
    "371": "Addition of the multiprocessing package to the ... by Noller, Oudkerk",
    "372": "Adding an ordered dictionary to collections by  Ronacher, Hettinger",
    "373": "Python 2.7 Release Schedule by  Peterson",
    "374": "Choosing a distributed VCS for the Python project by  Cannon, Turnbull, Vassalotti, Warsaw, Ochtman",
    "375": "Python 3.1 Release Schedule by  Peterson",
    "376": "Database of Installed Python Distributions by Ziadé",
    "377": "Allow __enter__() methods to skip the statement body by Coghlan",
    "378": "Format Specifier for Thousands Separator by Hettinger",
    "379": "Adding an Assignment Expression by  Whitley",
    "380": "Syntax for Delegating to a Subgenerator by  Ewing",
    "381": "Mirroring infrastructure for PyPI by  Ziadé, v. Löwis",
    "382": "Namespace Packages by v. Löwis",
    "383": "Non-decodable Bytes in System Character Interfaces by v. Löwis",
    "384": "Defining a Stable ABI by  v. Löwis",
    "385": "Migrating from Subversion to Mercurial by Ochtman, Pitrou, Brandl",
    "386": "Changing the version comparison module in Distutils by  Ziadé",
    "387": "Backwards Compatibility Policy by Peterson",
    "389": "argparse - New Command Line Parsing Module by Bethard",
    "390": "Static metadata for Distutils by  Ziadé",
    "391": "Dictionary-Based Configuration For Logging by Sajip",
    "392": "Python 3.2 Release Schedule by  Brandl",
    "393": "Flexible String Representation by v. Löwis",
    "394": "The 'python' command on Unix-Like Systems by  Staley, Coghlan",
    "395": "Module Aliasing by  Coghlan",
    "396": "Module Version Numbers by Warsaw",
    "397": "Python launcher for Windows by  Hammond",
    "398": "Python 3.3 Release Schedule by  Brandl",
    "399": "Pure Python/C Accelerator Module Compatibility ... by Cannon",
    "401": "BDFL Retirement by  Warsaw, Cannon",
    "444": "Python Web3 Interface by  McDonough, Ronacher",
    "666": "Reject Foolish Indentation by Creighton",
    "754": "Floating Point Special Values by Warnes",
    "3000": "Python 3000 by GvR",
    "3001": "Procedure for reviewing and improving standard ... by Brandl",
    "3002": "Procedure for Backwards-Incompatible Changes by Bethard",
    "3003": "Python Language Moratorium by Cannon, Noller, GvR",
    "3099": "Things that will Not Change in Python 3000 by Brandl",
    "3100": "Miscellaneous Python 3.0 Plans by Cannon",
    "3101": "Advanced String Formatting by Talin",
    "3102": "Keyword-Only Arguments by Talin",
    "3103": "A Switch/Case Statement by  GvR",
    "3104": "Access to Names in Outer Scopes by  Yee",
    "3105": "Make print a function by  Brandl",
    "3106": "Revamping dict.keys(), .values() and .items() by  GvR",
    "3107": "Function Annotations by Winter, Lownds",
    "3108": "Standard Library Reorganization by  Cannon",
    "3109": "Raising Exceptions in Python 3000 by  Winter",
    "3110": "Catching Exceptions in Python 3000 by Winter",
    "3111": "Simple input built-in in Python 3000 by Roberge",
    "3112": "Bytes literals in Python 3000 by  Orendorff",
    "3113": "Removal of Tuple Parameter Unpacking by Cannon",
    "3114": "Renaming iterator.next() to iterator.__next__() by  Yee",
    "3115": "Metaclasses in Python 3000 by Talin",
    "3116": "New I/O by  Stutzbach, GvR, Verdone",
    "3117": "Postfix type declarations by  Brandl",
    "3118": "Revising the buffer protocol by Oliphant, Banks",
    "3119": "Introducing Abstract Base Classes by  GvR, Talin",
    "3120": "Using UTF-8 as the default source encoding by von Löwis",
    "3121": "Extension Module Initialization and Finalization by von Löwis",
    "3122": "Delineation of the main module by Cannon",
    "3123": "Making PyObject_HEAD conform to standard C by von Löwis",
    "3124": "Overloading, Generic Functions, Interfaces, and ... by  Eby",
    "3125": "Remove Backslash Continuation by  Jewett",
    "3126": "Remove Implicit String Concatenation by Jewett, Hettinger",
    "3127": "Integer Literal Support and Syntax by Maupin",
    "3128": "BList: A Faster List-like Type by Stutzbach",
    "3129": "Class Decorators by Winter",
    "3130": "Access to Current Module/Class/Function by  Jewett",
    "3131": "Supporting Non-ASCII Identifiers by von Löwis",
    "3132": "Extended Iterable Unpacking by  Brandl",
    "3133": "Introducing Roles by  Winter",
    "3134": "Exception Chaining and Embedded Tracebacks by Yee",
    "3135": "New Super by  Spealman, Delaney, Ryan",
    "3136": "Labeled break and continue by Chisholm",
    "3137": "Immutable Bytes and Mutable Buffer by GvR",
    "3138": "String representation in Python 3000 by Ishimoto",
    "3139": "Cleaning out sys and the 'interpreter' module by  Peterson",
    "3140": "str(container) should call str(item), not repr(item) by Broytmann, Jewett",
    "3141": "A Type Hierarchy for Numbers by Yasskin",
    "3142": "Add a 'while' clause to generator expressions by  Britton",
    "3143": "Standard daemon process library by  Finney",
    "3144": "IP Address Manipulation Library for the Python ... by Moody",
    "3145": "Asynchronous I/O For subprocess.Popen by  Pruitt, McCreary, Carlson",
    "3146": "Merging Unladen Swallow into CPython by Winter, Yasskin, Kleckner",
    "3147": "PYC Repository Directories by Warsaw",
    "3148": "futures - execute computations asynchronously by  Quinlan",
    "3149": "ABI version tagged .so files by Warsaw",
    "3150": "Statement local namespaces (aka 'given' clause) by  Coghlan",
    "3151": "Reworking the OS and IO exception hierarchy by  Pitrou",
    "3152": "Cofunctions by  Ewing",
    "3333": "Python Web Server Gateway Interface v1.0.1 by Eby"
}