PEP_INDEX = {
    "1": "PEP Purpose and Guidelines                              Warsaw, Hylton, Goodger",
    "2": "Procedure for Adding New Modules                        Faassen",
    "4": "Deprecation of Standard Modules                         von Löwis",
    "5": "Guidelines for Language Evolution                       Prescod",
    "9": "Sample Plaintext PEP Template                           Warsaw",
    "10": "Voting Guidelines                                       Warsaw",
    "11": "Removing support for little used platforms              von Löwis",
    "12": "Sample reStructuredText PEP Template                    Goodger, Warsaw",
    "387": "Backwards Compatibility Policy                          Peterson",
    "20": "The Zen of Python                                       Peters",
    "42": "Feature Requests                                        Hylton",
    "8": "Style Guide for Python Code                             GvR, Warsaw",
    "257": "Docstring Conventions                                   Goodger, GvR",
    "7": "Style Guide for C Code                                  GvR",
    "6": "Bug Fix Releases                                        Aahz, Baxter",
    "101": "Doing Python Releases 101                          Warsaw, GvR",
    "360": "Externally Maintained Packages                          Cannon",
    "373": "Python 2.7 Release Schedule                             Peterson",
    "375": "Python 3.1 Release Schedule                             Peterson",
    "392": "Python 3.2 Release Schedule                             Brandl",
    "398": "Python 3.3 Release Schedule                             Brandl",
    "160": "Python 1.6 Release Schedule                             Drake",
    "200": "Python 2.0 Release Schedule                             Hylton",
    "226": "Python 2.1 Release Schedule                             Hylton",
    "251": "Python 2.2 Release Schedule                             Warsaw, GvR",
    "283": "Python 2.3 Release Schedule                             GvR",
    "320": "Python 2.4 Release Schedule                             Warsaw, Hettinger, Baxter",
    "356": "Python 2.5 Release Schedule                             Norwitz, GvR, Baxter",
    "361": "Python 2.6 and 3.0 Release Schedule                     Norwitz, Warsaw",
    "374": "Choosing a distributed VCS for the Python project       Cannon, Turnbull, Vassalotti, Warsaw, Ochtman",
    "385": "Migrating from Subversion to Mercurial                  Ochtman, Pitrou, Brandl",
    "347": "Migrating the Python CVS to Subversion                  von Löwis",
    "3000": "Python 3000                                            GvR",
    "3002": "Procedure for Backwards-Incompatible Changes            Bethard",
    "3003": "Python Language Moratorium                              Cannon, Noller, GvR",
    "3099": "Things that will Not Change in Python 3000              Brandl",
    "3001": "Procedure for reviewing and improving standard ...      Brandl",
    "3100": "Miscellaneous Python 3.0 Plans                          Cannon",
    "290": "Code Migration and Modernization                        Hettinger",
    "380": "Syntax for Delegating to a Subgenerator                 Ewing",
    "3152": "Cofunctions                                             Ewing",
    "342": "Coroutines via Enhanced Generators                      GvR, Eby",
    "220": "Coroutines, Generators, Continuations                   McMillan",
    "247": "API for Cryptographic Hash Functions                    Kuchling",
    "272": "API for Block Encryption Algorithms v1.0                Kuchling",
    "248": "Python Database API Specification v1.0                  Lemburg",
    "249": "Python Database API Specification v2.0                  Lemburg",
    "287": "reStructuredText Docstring Format                       Goodger",
    "3124": "Overloading, Generic Functions, Interfaces, and ...     Eby",
    "369": "Post import hooks                                       Heimes",
    "302": "New Import Hooks                                        JvR, Moore",
    "3124": "Overloading, Generic Functions, Interfaces, and ...     Eby",
    "3119": "Introducing Abstract Base Classes                       GvR, Talin",
    "246": "Object Adaptation                                       Martelli, Evans",
    "3133": "Introducing Roles                                       Winter",
    "333": "Python Web Server Gateway Interface v1.0                Eby",
    "3333": "Python Web Server Gateway Interface v1.0.1              Eby",
    "1": "PEP Purpose and Guidelines                              Warsaw, Hylton, Goodger",
    "2": "Procedure for Adding New Modules                        Faassen",
    "3": "Guidelines for Handling Bug Reports                     Hylton",
    "4": "Deprecation of Standard Modules                         von Löwis",
    "5": "Guidelines for Language Evolution                       Prescod",
    "6": "Bug Fix Releases                                        Aahz, Baxter",
    "7": "Style Guide for C Code                                  GvR",
    "8": "Style Guide for Python Code                             GvR, Warsaw",
    "9": "Sample Plaintext PEP Template                           Warsaw",
    "10": "Voting Guidelines                                       Warsaw",
    "11": "Removing support for little used platforms              von Löwis",
    "12": "Sample reStructuredText PEP Template                    Goodger, Warsaw",
    "20": "The Zen of Python                                       Peters",
    "42": "Feature Requests                                        Hylton",
    "100": "Python Unicode Integration                              Lemburg",
    "102": "Doing Python Micro Releases                             Baxter, Warsaw, GvR",
    "160": "Python 1.6 Release Schedule                             Drake",
    "200": "Python 2.0 Release Schedule                             Hylton",
    "201": "Lockstep Iteration                                      Warsaw",
    "202": "List Comprehensions                                     Warsaw",
    "203": "Augmented Assignments                                   Wouters",
    "204": "Range Literals                                          Wouters",
    "205": "Weak References                                         Drake",
    "206": "Python Advanced Library                                 Kuchling",
    "207": "Rich Comparisons                                        GvR, Ascher",
    "208": "Reworking the Coercion Model                            Schemenauer, Lemburg",
    "209": "Multi-dimensional Arrays                                Barrett, Oliphant",
    "210": "Decoupling the Interpreter Loop                         Ascher",
    "211": "Adding A New Outer Product Operator                     Wilson",
    "212": "Loop Counter Iteration                                  Schneider-Kamp",
    "213": "Attribute Access Handlers                               Prescod",
    "214": "Extended Print Statement                                Warsaw",
    "215": "String Interpolation                                    Yee",
    "216": "Docstring Format                                        Zadka",
    "217": "Display Hook for Interactive Use                        Zadka",
    "218": "Adding a Built-In Set Object Type                       Wilson, Hettinger",
    "219": "Stackless Python                                        McMillan",
    "220": "Coroutines, Generators, Continuations                   McMillan",
    "221": "Import As                                               Wouters",
    "222": "Web Library Enhancements                                Kuchling",
    "223": "Change the Meaning of \\x Escapes                        Peters",
    "224": "Attribute Docstrings                                    Lemburg",
    "225": "Elementwise/Objectwise Operators                        Zhu, Lielens",
    "226": "Python 2.1 Release Schedule                             Hylton",
    "227": "Statically Nested Scopes                                Hylton",
    "228": "Reworking Python's Numeric Model                        Zadka, GvR",
    "229": "Using Distutils to Build Python                         Kuchling",
    "230": "Warning Framework                                       GvR",
    "231": "__findattr__()                                          Warsaw",
    "232": "Function Attributes                                     Warsaw",
    "233": "Python Online Help                                      Prescod",
    "234": "Iterators                                               Yee, GvR",
    "235": "Import on Case-Insensitive Platforms                    Peters",
    "236": "Back to the __future__                                  Peters",
    "237": "Unifying Long Integers and Integers                     Zadka, GvR",
    "238": "Changing the Division Operator                          Zadka, GvR",
    "239": "Adding a Rational Type to Python                        Craig, Zadka",
    "240": "Adding a Rational Literal to Python                     Craig, Zadka",
    "241": "Metadata for Python Software Packages                   Kuchling",
    "242": "Numeric Kinds                                           Dubois",
    "243": "Module Repository Upload Mechanism                      Reifschneider",
    "244": "The `directive' statement                               von Löwis",
    "245": "Python Interface Syntax                                 Pelletier",
    "246": "Object Adaptation                                       Martelli, Evans",
    "247": "API for Cryptographic Hash Functions                    Kuchling",
    "248": "Python Database API Specification v1.0                  Lemburg",
    "249": "Python Database API Specification v2.0                  Lemburg",
    "250": "Using site-packages on Windows                          Moore",
    "251": "Python 2.2 Release Schedule                             Warsaw, GvR",
    "252": "Making Types Look More Like Classes                     GvR",
    "253": "Subtyping Built-in Types                                GvR",
    "254": "Making Classes Look More Like Types                     GvR",
    "255": "Simple Generators                                       Schemenauer, Peters, Hetland",
    "256": "Docstring Processing System Framework                   Goodger",
    "257": "Docstring Conventions                                   Goodger, GvR",
    "258": "Docutils Design Specification                           Goodger",
    "259": "Omit printing newline after newline                     GvR",
    "260": "Simplify xrange()                                       GvR",
    "261": "Support for 'wide' Unicode characters                   Prescod",
    "262": "A Database of Installed Python Packages                 Kuchling",
    "263": "Defining Python Source Code Encodings                   Lemburg, von Löwis",
    "264": "Future statements in simulated shells                   Hudson",
    "265": "Sorting Dictionaries by Value                           Griffin",
    "266": "Optimizing Global Variable/Attribute Access             Montanaro",
    "267": "Optimized Access to Module Namespaces                   Hylton",
    "268": "Extended HTTP functionality and WebDAV                  Stein",
    "269": "Pgen Module for Python                                  Riehl",
    "270": "uniq method for list objects                            Petrone",
    "271": "Prefixing sys.path by command line option               Giacometti",
    "272": "API for Block Encryption Algorithms v1.0                Kuchling",
    "273": "Import Modules from Zip Archives                        Ahlstrom",
    "274": "Dict Comprehensions                                     Warsaw",
    "275": "Switching on Multiple Values                            Lemburg",
    "276": "Simple Iterator for ints                                Althoff",
    "277": "Unicode file name support for Windows NT                Hodgson",
    "278": "Universal Newline Support                               Jansen",
    "279": "The enumerate() built-in function                       Hettinger",
    "280": "Optimizing access to globals                            GvR",
    "281": "Loop Counter Iteration with range and xrange            Hetland",
    "282": "A Logging System                                        Sajip, Mick",
    "283": "Python 2.3 Release Schedule                             GvR",
    "284": "Integer for-loops                                       Eppstein, Ewing",
    "285": "Adding a bool type                                      GvR",
    "286": "Enhanced Argument Tuples                                von Löwis",
    "287": "reStructuredText Docstring Format                       Goodger",
    "288": "Generators Attributes and Exceptions                    Hettinger",
    "289": "Generator Expressions                                   Hettinger",
    "290": "Code Migration and Modernization                        Hettinger",
    "291": "Backward Compatibility for the Python 2 Standard ...    Norwitz",
    "292": "Simpler String Substitutions                            Warsaw",
    "293": "Codec Error Handling Callbacks                          Dörwald",
    "294": "Type Names in the types Module                          Tirosh",
    "295": "Interpretation of multiline string constants            Koltsov",
    "296": "Adding a bytes Object Type                              Gilbert",
    "297": "Support for System Upgrades                             Lemburg",
    "298": "The Locked Buffer Interface                             Heller",
    "299": "Special __main__() function in modules                  Epler",
    "301": "Package Index and Metadata for Distutils                Jones",
    "302": "New Import Hooks                                        JvR, Moore",
    "303": "Extend divmod() for Multiple Divisors                   Bellman",
    "304": "Controlling Generation of Bytecode Files                Montanaro",
    "305": "CSV File API                                            Altis, Cole, McNamara, Montanaro, Wells",
    "306": "How to Change Python's Grammar                          Hudson, Diederich, Coghlan, Peterson",
    "307": "Extensions to the pickle protocol                       GvR, Peters",
    "308": "Conditional Expressions                                 GvR, Hettinger",
    "309": "Partial Function Application                            Harris",
    "310": "Reliable Acquisition/Release Pairs                      Hudson, Moore",
    "311": "Simplified Global Interpreter Lock Acquisition for ...  Hammond",
    "312": "Simple Implicit Lambda                                  Suzi, Martelli",
    "313": "Adding Roman Numeral Literals to Python                 Meyer",
    "314": "Metadata for Python Software Packages v1.1              Kuchling, Jones",
    "315": "Enhanced While Loop                                     Hettinger, Carroll",
    "316": "Programming by Contract for Python                      Way",
    "317": "Eliminate Implicit Exception Instantiation              Taschuk",
    "318": "Decorators for Functions and Methods                    Smith",
    "319": "Python Synchronize/Asynchronize Block                   Pelletier",
    "320": "Python 2.4 Release Schedule                             Warsaw, Hettinger, Baxter",
    "321": "Date/Time Parsing and Formatting                        Kuchling",
    "322": "Reverse Iteration                                       Hettinger",
    "323": "Copyable Iterators                                      Martelli",
    "324": "subprocess - New process module                         Astrand",
    "325": "Resource-Release Support for Generators                 Pedroni",
    "326": "A Case for Top and Bottom Values                        Carlson, Reedy",
    "327": "Decimal Data Type                                       Batista",
    "328": "Imports: Multi-Line and Absolute/Relative               Aahz",
    "329": "Treating Builtins as Constants in the Standard Library  Hettinger",
    "330": "Python Bytecode Verification                            Pelletier",
    "331": "Locale-Independent Float/String Conversions             Reis",
    "332": "Byte vectors and String/Unicode Unification             Montanaro",
    "333": "Python Web Server Gateway Interface v1.0                Eby",
    "334": "Simple Coroutines via SuspendIteration                  Evans",
    "335": "Overloadable Boolean Operators                          Ewing",
    "336": "Make None Callable                                      McClelland",
    "337": "Logging Usage in the Standard Library                   Dubner",
    "338": "Executing modules as scripts                            Coghlan",
    "339": "Design of the CPython Compiler                          Cannon",
    "340": "Anonymous Block Statements                              GvR",
    "341": "Unifying try-except and try-finally                     Brandl",
    "342": "Coroutines via Enhanced Generators                      GvR, Eby",
    "343": "The 'with' Statement                                    GvR, Coghlan",
    "344": "Exception Chaining and Embedded Tracebacks              Yee",
    "345": "Metadata for Python Software Packages 1.2               Jones",
    "346": "User Defined ('``with``') Statements                    Coghlan",
    "347": "Migrating the Python CVS to Subversion                  von Löwis",
    "348": "Exception Reorganization for Python 3.0                 Cannon",
    "349": "Allow str() to return unicode strings                   Schemenauer",
    "350": "Codetags                                                Elliott",
    "351": "The freeze protocol                                     Warsaw",
    "352": "Required Superclass for Exceptions                      Cannon, GvR",
    "353": "Using ssize_t as the index type                         von Löwis",
    "354": "Enumerations in Python                                  Finney",
    "355": "Path - Object oriented filesystem paths                 Lindqvist",
    "356": "Python 2.5 Release Schedule                             Norwitz, GvR, Baxter",
    "357": "Allowing Any Object to be Used for Slicing              Oliphant",
    "358": "The 'bytes' Object                                      Schemenauer, GvR",
    "359": "The 'make' Statement                                    Bethard",
    "360": "Externally Maintained Packages                          Cannon",
    "361": "Python 2.6 and 3.0 Release Schedule                     Norwitz, Warsaw",
    "362": "Function Signature Object                               Cannon, Seo",
    "363": "Syntax For Dynamic Attribute Access                     North",
    "364": "Transitioning to the Py3K Standard Library              Warsaw",
    "365": "Adding the pkg_resources module                         Eby",
    "366": "Main module explicit relative imports                   Coghlan",
    "367": "New Super                                               Spealman, Delaney",
    "368": "Standard image protocol and class                       Mastrodomenico",
    "369": "Post import hooks                                       Heimes",
    "370": "Per user site-packages directory                        Heimes",
    "371": "Addition of the multiprocessing package to the ...      Noller, Oudkerk",
    "372": "Adding an ordered dictionary to collections             Ronacher, Hettinger",
    "373": "Python 2.7 Release Schedule                             Peterson",
    "374": "Choosing a distributed VCS for the Python project       Cannon, Turnbull, Vassalotti, Warsaw, Ochtman",
    "375": "Python 3.1 Release Schedule                             Peterson",
    "376": "Database of Installed Python Distributions              Ziadé",
    "377": "Allow __enter__() methods to skip the statement body    Coghlan",
    "378": "Format Specifier for Thousands Separator                Hettinger",
    "379": "Adding an Assignment Expression                         Whitley",
    "380": "Syntax for Delegating to a Subgenerator                 Ewing",
    "381": "Mirroring infrastructure for PyPI                       Ziadé, v. Löwis",
    "382": "Namespace Packages                                      v. Löwis",
    "383": "Non-decodable Bytes in System Character Interfaces      v. Löwis",
    "384": "Defining a Stable ABI                                   v. Löwis",
    "385": "Migrating from Subversion to Mercurial                  Ochtman, Pitrou, Brandl",
    "386": "Changing the version comparison module in Distutils     Ziadé",
    "387": "Backwards Compatibility Policy                          Peterson",
    "389": "argparse - New Command Line Parsing Module              Bethard",
    "390": "Static metadata for Distutils                           Ziadé",
    "391": "Dictionary-Based Configuration For Logging              Sajip",
    "392": "Python 3.2 Release Schedule                             Brandl",
    "393": "Flexible String Representation                          v. Löwis",
    "394": "The 'python' command on Unix-Like Systems               Staley, Coghlan",
    "395": "Module Aliasing                                         Coghlan",
    "396": "Module Version Numbers                                  Warsaw",
    "397": "Python launcher for Windows                             Hammond",
    "398": "Python 3.3 Release Schedule                             Brandl",
    "399": "Pure Python/C Accelerator Module Compatibility ...      Cannon",
    "401": "BDFL Retirement                                         Warsaw, Cannon",
    "444": "Python Web3 Interface                                   McDonough, Ronacher",
    "666": "Reject Foolish Indentation                              Creighton",
    "754": "Floating Point Special Values                  Warnes",
    "3001": "Procedure for reviewing and improving standard ...      Brandl",
    "3002": "Procedure for Backwards-Incompatible Changes            Bethard",
    "3003": "Python Language Moratorium                              Cannon, Noller, GvR",
    "3099": "Things that will Not Change in Python 3000              Brandl",
    "3100": "Miscellaneous Python 3.0 Plans                          Cannon",
    "3101": "Advanced String Formatting                              Talin",
    "3102": "Keyword-Only Arguments                                  Talin",
    "3103": "A Switch/Case Statement                                 GvR",
    "3104": "Access to Names in Outer Scopes                         Yee",
    "3105": "Make print a function                                   Brandl",
    "3106": "Revamping dict.keys(), .values() and .items()           GvR",
    "3107": "Function Annotations                                    Winter, Lownds",
    "3108": "Standard Library Reorganization                         Cannon",
    "3109": "Raising Exceptions in Python 3000                       Winter",
    "3110": "Catching Exceptions in Python 3000                      Winter",
    "3111": "Simple input built-in in Python 3000                    Roberge",
    "3112": "Bytes literals in Python 3000                           Orendorff",
    "3113": "Removal of Tuple Parameter Unpacking                    Cannon",
    "3114": "Renaming iterator.next() to iterator.__next__()         Yee",
    "3115": "Metaclasses in Python 3000                              Talin",
    "3116": "New I/O                                                 Stutzbach, GvR, Verdone",
    "3117": "Postfix type declarations                               Brandl",
    "3118": "Revising the buffer protocol                            Oliphant, Banks",
    "3119": "Introducing Abstract Base Classes                       GvR, Talin",
    "3120": "Using UTF-8 as the default source encoding              von Löwis",
    "3121": "Extension Module Initialization and Finalization        von Löwis",
    "3122": "Delineation of the main module                          Cannon",
    "3123": "Making PyObject_HEAD conform to standard C              von Löwis",
    "3124": "Overloading, Generic Functions, Interfaces, and ...     Eby",
    "3125": "Remove Backslash Continuation                           Jewett",
    "3126": "Remove Implicit String Concatenation                    Jewett, Hettinger",
    "3127": "Integer Literal Support and Syntax                      Maupin",
    "3128": "BList: A Faster List-like Type                          Stutzbach",
    "3129": "Class Decorators                                        Winter",
    "3130": "Access to Current Module/Class/Function                 Jewett",
    "3131": "Supporting Non-ASCII Identifiers                        von Löwis",
    "3132": "Extended Iterable Unpacking                             Brandl",
    "3133": "Introducing Roles                                       Winter",
    "3134": "Exception Chaining and Embedded Tracebacks              Yee",
    "3135": "New Super                                               Spealman, Delaney, Ryan",
    "3136": "Labeled break and continue                              Chisholm",
    "3137": "Immutable Bytes and Mutable Buffer                      GvR",
    "3138": "String representation in Python 3000                    Ishimoto",
    "3139": "Cleaning out sys and the 'interpreter' module           Peterson",
    "3140": "str(container) should call str(item), not repr(item)    Broytmann, Jewett",
    "3141": "A Type Hierarchy for Numbers                            Yasskin",
    "3142": "Add a 'while' clause to generator expressions           Britton",
    "3143": "Standard daemon process library                         Finney",
    "3144": "IP Address Manipulation Library for the Python ...      Moody",
    "3145": "Asynchronous I/O For subprocess.Popen                   Pruitt, McCreary, Carlson",
    "3146": "Merging Unladen Swallow into CPython                    Winter, Yasskin, Kleckner",
    "3147": "PYC Repository Directories                              Warsaw",
    "3148": "futures - execute computations asynchronously           Quinlan",
    "3149": "ABI version tagged .so files                            Warsaw",
    "3150": "Statement local namespaces (aka 'given' clause)         Coghlan",
    "3151": "Reworking the OS and IO exception hierarchy             Pitrou",
    "3152": "Cofunctions                                             Ewing",
    "3333": "Python Web Server Gateway Interface v1.0.1              Eby"
}
